-- To include:
-- love.mouse.getCursor
-- love.mouse.getPosition
-- love.mouse.getX
-- love.mouse.getY
-- love.mouse.isDown
-- love.mouse.isGrabbed
-- love.mousepressed
-- love.mousereleased
-- love.mousemoved